#!/usr/bin/env sh

set -e

docker run \
    -v /usr/local/bin/:/usr/local/bin/ \
    --rm \
        --env=AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
        --env=AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
        --env=AWS_REGION=${AWS_REGION} \
        --env=AWS_S3_ARCHIVE_BUCKET_NAME=${AWS_S3_ARCHIVE_BUCKET_NAME} \
        --env=DIGITALOCEAN_ACCESS_TOKEN=${DIGITALOCEAN_ACCESS_TOKEN} \
        --env=GLASSDOOR_USERNAME=${GLASSDOOR_USERNAME} \
        --env=GLASSDOOR_PASSWORD=${GLASSDOOR_PASSWORD} \
        --env=REDIS_MODE=${REDIS_MODE} \
        --env=REDIS_CUSTOM_HOST=${REDIS_CUSTOM_HOST} \
        --env=REDIS_PORT=${REDIS_PORT} \
        --env=REDIS_PASSWORD=${REDIS_PASSWORD} \
        --env=SUPERVISOR_PUBSUB_REDIS_DB=${SUPERVISOR_PUBSUB_REDIS_DB} \
        --env=SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL} \
        --env=DEBUG=${DEBUG} \
        --env=CROSS_SESSION_TIME_LIMIT_MINUTES=${CROSS_SESSION_TIME_LIMIT_MINUTES} \
        --env=LOGGER_LEVEL=${LOGGER_LEVEL} \
        --env=SCRAPER_MODE=${SCRAPER_MODE} \
        --env=TEST_COMPANY_INFORMATION_STRING=${TEST_COMPANY_INFORMATION_STRING} \
        --env=TEST_COMPANY_ID=${TEST_COMPANY_ID} \
        --env=TEST_COMPANY_NAME=${TEST_COMPANY_NAME} \
        --env=TEST_COMPANY_LAST_PROGRESS_PROCESSED=${TEST_COMPANY_LAST_PROGRESS_PROCESSED} \
        --env=TEST_COMPANY_LAST_PROGRESS_WENTTHROUGH=${TEST_COMPANY_LAST_PROGRESS_WENTTHROUGH} \
        --env=TEST_COMPANY_LAST_PROGRESS_TOTAL=${TEST_COMPANY_LAST_PROGRESS_TOTAL} \
        --env=TEST_COMPANY_LAST_PROGRESS_DURATION=${TEST_COMPANY_LAST_PROGRESS_DURATION} \
        --env=TEST_COMPANY_LAST_PROGRESS_PAGE=${TEST_COMPANY_LAST_PROGRESS_PAGE} \
        --env=TEST_COMPANY_LAST_PROGRESS_SESSION=${TEST_COMPANY_LAST_PROGRESS_SESSION} \
        --env=TEST_COMPANY_LAST_REVIEW_PAGE_URL=${TEST_COMPANY_LAST_REVIEW_PAGE_URL} \
    shaungc/gd-scraper:latest
